### ISSUE TITLE
implement "why" subcommand

### ISSUE THREAD

**Issue by tylerslaton** [benluddy/depster#14]
# User Story
As a cluster admin,
I want to be able to understand why a particular resource was created
So that I can understand its dependencies

# Summary
As per Ben Luddy: 

> It has been requested to implement something like `apt-get autoremove` before, which removes stuff that was only installed because it was a dependency(direct or transitive) of something that you explicitly asked to install. Maybe a depster why for understanding what breaks if you remove something from the input.

To be clear, we aren't implementing the `autoremove` functionality that Ben mentions here. Instead, we are adding functionality that allows us to understand why a particular resource exists and what relies on it.

I envision this UX looking somewhat like this:

```console
$ depster why deployment combo-demployment
subscription - combo-subscription
installplan - combo-installplan
```

In this command, an assumption is being made that a tangible connection to the cluster is being made to read resources from it. This should be able to determine if a particular cluster resource was brought in by an OLM resolution. If it was, it should also be able to determine if the specified input is a dependency of it. 

- [x] Document UX/approach for building out `depster why` subcommand
- [ ] Manually attempt to understand what brought a particular resource
- [ ] Create a shell script to automate manual process
- [ ] Create a subcommand to do logic of script

**Comment by jbuchananr** [comment]
Initial draft: 
![depster_why drawio (1)](https://user-images.githubusercontent.com/47618606/159044199-ed6575c5-6dfd-44c8-87cd-ebd257847971.png)

**Comment by jbuchananr** [comment]
# manual process of implementation of "why command"
## Overview 

The depster why subcommand must be able to retrieve all OLM related resources of the given resources such as what it is owned by and what it owns. The goal of the depster why command is to be able to start to understand why certain dependencies/resources are installed and how the relate to other resources. An example of this, would be if you want to delete a resource you can run `$ depster why ...` to get an idea what also will be affected once the resource is deleted. 

Example of how this command will look: `$ ./depster why NAMESPACE TYPE_OF_RESOURCE NAME_OF_RESOURCE`

### Thought / Possible functionatlity
Do we want to do a recursive approach on other resources? E.g. If we find a owner reference to another resource, would we also want to check that resource for OLM labels/another owner reference. This also could be set with a command such as `$ ./depster why -r ...`

## Process
* Check if resource exists 
* Describe resource
* Output metadata(yaml) of resource to find ownerReference
* Find ownerReference/labels that are OLM related
* If resources(owner/labels) exist output them

#### EXAMPLE
`$ ./depster why olm pod cockroach-db`

**Step 1:**
* Ensure resource exists
    * `$ kubectl get pod -n olm cochroach-db`
* Find OLM related labels  
    * `$ kubectl describe pod -n olm cockroach-db`
    * `$ kubectl describe pod -n olm cockroach-db | grep Labels:`
    Output: 
    * `Labels:       olm.catalogSource=cockroach-db`
* Find *OwnerReference* of resource
    * `$ kubectl get pod -n olm cockroach-db -o yaml` 
    Output: (only ownerReference & labels shown)
    *  ```
        labels:
            olm.catalogSource: cockroach-db
            olm.pod-spec-hash: 579fffb574
          name: cockroach-db-xd4nj
          namespace: default
          ownerReferences:
          - apiVersion: operators.coreos.com/v1alpha1
            blockOwnerDeletion: false
            controller: false
            kind: CatalogSource
            name: cockroach-db
            uid: a474f1e8-e76b-40f0-8de8-e5295d50250f
          resourceVersion: "10842"
          uid: d5becd0f-be98-4f03-a443-e3c6c1f4cdf2
        ```
We see that an `olm` catalogSource owns this pod.

**Step 2:**
*  Ensure related/owner resource exists
    * `$ kubectl get catalogsource -n olm cockroach-db`
    * IF resource found then RETURN catalog resource ELSE return NONE

**Step 3:**
* Output resources found
Example output:  
```
$ RESOURCE        NAMESPACE    TYPE 
$ cochroach-db     OLM         catsrc
```
## Next Steps
Next, this manual process will be implemented in a shell script that takes in three variables that are NAMESPACE, TYPE, and NAME. 

e.g. `$ ./shell.sh default pod cochroach-db-xyz`

This will start as a bare bones shell script, but as the UX is ironed out it eventually will be implemented as a sub command in the depster CLI.

**Comment by benluddy** [comment]
This isn't really within the scope of dependency resolution (and by extension, depster). What I had suggested was that, given a set of installed operators and selecting one element of that set, output the constraints being satisfied by that element. In other words, if that operator were to be removed, and automatic dependency subscription creation did not exist, what error (i.e. set of unsatisfiable constraints) would a resolution cycle produce?

**Comment by tylerslaton** [comment]
@benluddy Appreciate the response while you're away! So just to get some clarification from you on that, we're talking about a situation where an operator (lets call it OperatorA) has some dependency (say OperatorB) that it brought along with it through resolution. Based on what you're saying, this `why` command should be responsible for looking at that dependency, OperatorB, (or any of a set if there are more than one) and seeing what constraints from existing operators would fail in another resolution cycle? In other words, if we were to remove OperatorB, what other operator would come looking for it (in this case OperatorA).
