### ISSUE TITLE
Document approach for building off-cluster resolution tool

### ISSUE THREAD

**Issue by tylerslaton** [benluddy/depster#18]
First step will be to think about _how_ we will go about doing this.

Some things to think about:

1. What does this request entail?
2. Based on the request, what technical challenges will come up?
3. In an ideal world, what would this process look like?

With all of this in mind, document a user would interact with the implemented off-cluster resolution tool. This will give you a path forward when implementing the other phases of the feature.

**Comment by jbuchananr** [comment]
Initial idea: 
![depsterUXdesign](https://user-images.githubusercontent.com/47618606/158816429-9d35825d-cbc1-4e53-863a-6d0cd8eaaa79.jpg)

**Comment by jbuchananr** [comment]
Second draft:
**FOCUSING ON RESOLVE ONLY**
![resolve](https://user-images.githubusercontent.com/47618606/158860047-4d94a17c-a1a3-4faf-a00d-748f3e087002.png)
